external_components:
  - source:
      type: git
      url: https://github.com/jourdant/esphome-zoneswitch
      ref: main
    components: [ "zoneswitch" ]
    refresh: 0s

uart:
  - id: zoneswitch_uart
    rx_pin: GPIO03
    tx_pin: GPIO04
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

zoneswitch:
  - id: zs_bus
    uart_id: zoneswitch_uart
    debug: false
    enable_polling: true

switch:
  - platform: zoneswitch
    id: zone_1_switch
    zoneswitch_id: zs_bus
    zone: 1
    name: "ZoneSwitch Zone 1"
    icon: mdi:air-filter

  - platform: zoneswitch
    id: zone_2_switch
    zoneswitch_id: zs_bus
    zone: 2
    name: "ZoneSwitch Zone 2"
    icon: mdi:air-filter

  - platform: zoneswitch
    id: zone_3_switch
    zoneswitch_id: zs_bus
    zone: 3
    name: "ZoneSwitch Zone 3"
    icon: mdi:air-filter

  - platform: zoneswitch
    id: zone_4_switch
    zoneswitch_id: zs_bus
    zone: 4
    name: "ZoneSwitch Zone 4"
    icon: mdi:air-filter

  - platform: zoneswitch
    id: zone_5_switch
    zoneswitch_id: zs_bus
    zone: 5
    name: "ZoneSwitch Zone 5"
    icon: mdi:air-filter

  - platform: zoneswitch
    id: zone_6_switch
    zoneswitch_id: zs_bus
    zone: 6
    name: "ZoneSwitch Zone 6"
    icon: mdi:air-filter

text_sensor:
  - platform: zoneswitch
    id: zoneswitch_node_address
    zoneswitch_id: zs_bus
    metric: node_address
    name: "ZoneSwitch Node Address"
    icon: mdi:identifier

binary_sensor:
  - platform: zoneswitch
    id: zoneswitch_online_status
    zoneswitch_id: zs_bus
    metric: online
    name: "ZoneSwitch Gateway Online"
    icon: mdi:lan-connect
